# Generated by Django 5.2.4 on 2025-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_title',
            field=models.CharField(default='Untitled Journal', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='response_text',
            field=models.TextField(default='this is a default text, should be removed later'),
            preserve_default=False,
        ),
    ]
