# Generated by Django 5.2.4 on 2025-07-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='journal_title',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='chat_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journals.chatsession'),
            preserve_default=False,
        ),
    ]
